version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.API
    container_name: API
    command: ["uvicorn", "API.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    networks:
      - plant_network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - plant_network

networks:
  plant_network:

volumes:
  db:
    driver: local
